### ISSUE TITLE
Not issue just a noob question 

### ISSUE THREAD

**Issue by elz64** [kinnairdclan/script.video.mkvripper#2]
Hi,
When you say makemv installed separately ... what does it means talking about  kodi running on a Raspbeey Pi2 (osmc)

??
Thank you

**Comment by kinnairdclan** [comment]
That simply means you need makemkv either installed either via its package supplied for Linux at http://www.makemkv.com/forum2/viewtopic.php?f=3&t=224, or it's openelec-provided plugin whose repository can be found here: https://github.com/OpenELEC/unofficial-addons.

There is a large amount of proprietary software running in makemkv binary, so I'm unsure whether or not it will compile successfully for the RPi2's ARM processor, then again, I've never tried it.

**Comment by elz64** [comment]
ok.

Thank you for the links I'll  checkt it out

2015-10-01 16:13 GMT+02:00 Jason Kinnard notifications@github.com:

**Comment by kinnairdclan** [comment]
No problem!
